"""Flight-trip table

Revision ID: 2afd16b9ca3d
Revises: fd657668e086
Create Date: 2022-12-18 12:55:41.224769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afd16b9ca3d'
down_revision = 'fd657668e086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id', 'flight_id', 'trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_trips')
    # ### end Alembic commands ###
