"""empty message

Revision ID: 991bfa14347c
Revises: a9abb25d6397
Create Date: 2022-12-19 13:26:36.525490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991bfa14347c'
down_revision = 'a9abb25d6397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('trips_flight_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'flights', ['flight_id'], ['id'])
        batch_op.drop_column('flight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('trips_flight_fkey', 'flights', ['flight'], ['id'])
        batch_op.drop_column('flight_id')

    # ### end Alembic commands ###
