"""City table

Revision ID: fd657668e086
Revises: bdcd3f8a2d56
Create Date: 2022-12-18 12:39:56.090516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd657668e086'
down_revision = 'bdcd3f8a2d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cities', ['orgin_id'], ['id'])
        batch_op.create_foreign_key(None, 'cities', ['destination_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('cities')
    # ### end Alembic commands ###
