"""User trips relational table

Revision ID: fb3a9b6fcc83
Revises: dfab17f2b2f3
Create Date: 2022-12-18 21:17:15.223338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3a9b6fcc83'
down_revision = 'dfab17f2b2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'trip_id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'hotels', ['hotel_id'], ['id'])
        batch_op.create_foreign_key(None, 'rental_cars', ['rental_car_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('user_trips')
    # ### end Alembic commands ###
