"""Airline table

Revision ID: 373490c51238
Revises: a94b1170b076
Create Date: 2022-12-18 21:14:28.322600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373490c51238'
down_revision = 'a94b1170b076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airlines')
    # ### end Alembic commands ###
