"""Hotel-Rental Cars FK

Revision ID: 294a58cd81cd
Revises: 02d2ca5684f9
Create Date: 2022-12-18 12:08:30.266136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294a58cd81cd'
down_revision = '02d2ca5684f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rental_car_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rental_cars', ['rental_car_id'], ['id'])
        batch_op.create_foreign_key(None, 'hotels', ['hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rental_car_id')
        batch_op.drop_column('hotel_id')

    # ### end Alembic commands ###
