"""Airlines table

Revision ID: bdcd3f8a2d56
Revises: 294a58cd81cd
Create Date: 2022-12-18 12:31:46.669571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcd3f8a2d56'
down_revision = '294a58cd81cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airline_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'airlines', ['airline_id'], ['id'])
        batch_op.drop_column('airline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airline', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('airline_id')

    op.drop_table('airlines')
    # ### end Alembic commands ###
