"""Flight-Trip relational table

Revision ID: d363748b0016
Revises: fb3a9b6fcc83
Create Date: 2022-12-18 21:23:43.146913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd363748b0016'
down_revision = 'fb3a9b6fcc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id', 'flight_id', 'trip_id')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'airlines', ['airline_id'], ['id'])
        batch_op.create_foreign_key(None, 'cities', ['destination_id'], ['id'])
        batch_op.create_foreign_key(None, 'cities', ['orgin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('flight_trips')
    # ### end Alembic commands ###
