"""empty message

Revision ID: a9abb25d6397
Revises: c87b0695c8c2
Create Date: 2022-12-19 13:19:24.568543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9abb25d6397'
down_revision = 'c87b0695c8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_trips')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'flights', ['flight'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flight')

    op.create_table('flight_trips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name='flight_trips_flight_id_fkey'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='flight_trips_trip_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'flight_id', 'trip_id', name='flight_trips_pkey')
    )
    # ### end Alembic commands ###
