"""flights table

Revision ID: 1051879d8f6b
Revises: 9ef3f825ce81
Create Date: 2023-01-17 19:47:46.422226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1051879d8f6b'
down_revision = '9ef3f825ce81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_num', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('rental_car_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['rental_car_id'], ['rental_cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_num')
    )
    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('trips')
    # ### end Alembic commands ###
